## Default values.yaml for Telegraf
## This is a YAML-formatted file.
## ref: https://hub.docker.com/r/library/telegraf/tags/
image:
  repo: "telegraf"
  tag: "1.10.0-alpine"
  pullPolicy: IfNotPresent

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 1

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Exposed telegraf configuration
## ref: https://docs.influxdata.com/telegraf/v1.8/administration/configuration/
config:
  # global_tags:
  #   cluster: "mycluster"
  agent:
    interval: "10s"
    round_interval: true
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    collection_jitter: "0s"
    flush_interval: "10s"
    flush_jitter: "0s"
  outputs:
    - influxdb:
        url: "https://2886795288-30082-cykoria04.environments.katacoda.com/"
        database: "telegraf"
        retention_policy: ""
        timeout: "5s"
        username: ""
        password: ""
        user_agent: "telegraf"
        insecure_skip_verify: false
  inputs:
    - kubernetes:
        url: "https://2886795288-6443-cykoria04.environments.katacoda.com"
        bearer_token: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        insecure_skip_verify: true
    - docker: 
        endpoint: "unix:///var/run/docker.sock"
        timeout: "5s"
        perdevice: true
        total: false
        docker_label_exclude:
          - "annotation.kubernetes.io/*"
    - prometheus:
        urls: ["https://2886795288-30080-cykoria04.environments.katacoda.com/metrics","https://2886795288-30081-cykoria04.environments.katacoda.com/metrics"]
    - cpu:
    - system:
    - disk:
    - diskio:
    - mem:
    - processes:
    - net:
    - swap:
    - cloudwatch:
        region: "us-east-1"
        access_key: ""
        secret_key: ""
        period: "5m"
        delay: "5m"
        interval: "5m"
        cache_ttl: "10m"
        ratelimit: 10
        namespace: "AWS/ELB"
    - cloudwatch:
        region: "us-east-1"
        access_key: ""
        secret_key: ""
        period: "5m"
        delay: "5m"
        interval: "5m"
        cache_ttl: "10m"
        ratelimit: 10
        namespace: "AWS/EC2"
    - cloudwatch:
        region: "us-east-1"
        access_key: ""
        secret_key: ""
        period: "5m"
        delay: "5m"
        interval: "5m"
        cache_ttl: "10m"
        ratelimit: 10
        namespace: "AWS/ELB"
  
