## Default values.yaml for Telegraf
## This is a YAML-formatted file.
## ref: https://hub.docker.com/r/library/telegraf/tags/
image:
  repo: "telegraf"
  tag: "1.10.0-alpine"
  pullPolicy: IfNotPresent

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 1

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
#
nodeSelector: {}

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Configure the service for this telegraf instance. If you are running
## Any of the service plugins you will need this enabled
## Service Plugins: http_listener, statsd, tcp_listener, udp_listener
## ref: http://kubernetes.io/docs/user-guide/services/
service:
  enabled: true
  type: NodePort
  
## Exposed telegraf configuration
## For full list of possible values see `/docs/all-config-values.yaml` and `/docs/all-config-values.toml`
## ref: https://docs.influxdata.com/telegraf/v1.8/administration/configuration/

config:
##    global_tags:
##      dc: "us-east-1"
##      user: "$USER"
  agent:
    interval: "10s"
    round_interval: true
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    collection_jitter: "0s"
    flush_interval: "10s"
    flush_jitter: "0s"
    precision: ""
    debug: false
    quiet: false
    logfile: ""
    hostname: "telegraf-polling-service"
    omit_hostname: false
  outputs:
    - influxdb:
        urls:
          - "https://2886795355-6443-ollie02.environments.katacoda.com:30082"
        database: "telegraf"
        username: "admin"
        password: "admin"

  inputs:
    - influxdb:
        urls:
          - "https://2886795355-30082-ollie02.environments.katacoda.com/debug/vars"
        timeout: "5s"
    - kapacitor:
        urls:
          - "https://2886795355-30083-ollie02.environments.katacoda.com"
        timeout: "5s"
    - kapacitor:
        urls:
          - "https://2886795355-30083-ollie02.environments.katacoda.com/debug/vars"
        timeout: "5s"
    - cpu:
    - system:
    - disk:
    - diskio:
    - mem:
    - processes:
    - net:
    - swap:
    - cloudwatch:
        region: "us-east-1"
        access_key: ""
        secret_key: ""
        period: "5m"
        delay: "5m"
        interval: "5m"
        cache_ttl: "10m"
        ratelimit: 10
        namespace: "AWS/ELB"
    - cloudwatch:
        region: "us-east-1"
        access_key: ""
        secret_key: ""
        period: "5m"
        delay: "5m"
        interval: "5m"
        cache_ttl: "10m"
        ratelimit: 10
        namespace: "AWS/EC2"
    - cloudwatch:
        region: "us-east-1"
        access_key: ""
        secret_key: ""
        period: "5m"
        delay: "5m"
        interval: "5m"
        cache_ttl: "10m"
        ratelimit: 10
        namespace: "AWS/ELB"
    - kube_inventory:
        url: "https://2886795355-6443-ollie02.environments.katacoda.com"
        namespace: ""
##      prometheus:
##        urls:
##          - "https://kubernetes.default:443/metrics"
##        name_prefix: "prom_"
##        bearer_token: "/var/run/secrets/kubernetes.io/serviceaccount/token"
##        insecure_skip_verify: true
##        ssl_ca: /path/to/cafile
##        ssl_cert: /path/to/certfile
##        ssl_key: /path/to/keyfile
##      http_listener:
##        service_address: ":8186"
##        read_timeout: "10s"
##        write_timeout: "10s"
##        max_body_size: 0
##        max_line_size: 0
    - statsd:
        service_address: ":8125"
        percentiles:
          - 50
          - 95
          - 99
        metric_separator: "_"
        allowed_pending_messages: 10000
        percentile_limit: 1000

